package com.theironyard.GameTrackerService;
import com.theironyard.Game;
import java.sql.*;
import java.util.ArrayList;

public class GameTrackerService {

    private final Connection connection;

    public GameTrackerService(Connection connection) {
        this.connection = connection;
    }

    //init database
    public void initDatabase() throws SQLException {
        Statement statement = connection.createStatement();
        statement.execute("CREATE TABLE IF NOT EXISTS game (id IDENTITY, name VARCHAR , platform VARCHAR, genre VARCHAR, releaseYear INT)");

    }

    //inserts game into database
    public void insertGame(Game game) throws SQLException {
        PreparedStatement statement = connection.prepareStatement("INSERT INTO game VALUES (NULL, ?, ?, ?, ?)");
        statement.setString(1, game.getName());
        statement.setString(2, game.getPlatform());
        statement.setString(3, game.getGenre());
        statement.setInt(4, game.getReleaseYear());
        statement.executeUpdate();

        //sets game.id to autogenerated id from SQL
        ResultSet resultSet = statement.getGeneratedKeys();
        resultSet.next();
        game.setId(resultSet.getInt(1));
        System.out.println(game.getId());
    }

    //delete game from database
    public void deleteGame(int id) throws SQLException{

        PreparedStatement statement = connection.prepareStatement("DELETE FROM game WHERE id = ?");
        statement.setInt(1, id);
        //returns int of row affected
        statement.executeUpdate();

    }

    //update game info
    public void updateGame(int id, String name, String platform, String genre, int releaseYear) throws SQLException{
        PreparedStatement statement = connection.prepareStatement("UPDATE game SET name = ?, platform = ?, genre = ?, releaseYear = ? WHERE id = ?");
        statement.setString(1, name);
        statement.setString(2, platform);
        statement.setString(3, genre);
        statement.setInt(4, releaseYear);
        statement.setInt(5, id);
        statement.executeUpdate();
    }

    //select game(s) from database and return arraylist of Games
    public ArrayList<Game> selectGames() throws SQLException{
        PreparedStatement statement = connection.prepareStatement("SELECT * FROM game");
        ResultSet resultSet = statement.executeQuery();
        ArrayList<Game> games = new ArrayList<>();

        while(resultSet.next()){

            Game game = new Game(

                    resultSet.getInt("id"),
                    resultSet.getString("name"),
                    resultSet.getString("platform"),
                    resultSet.getString("genre"),
                    resultSet.getInt("releaseYear")
            );

            games.add(game);

        }

        return games;

    }

    public ArrayList<Game> searchGame(String query) throws SQLException {

        PreparedStatement statement = connection.prepareStatement("SELECT * FROM game WHERE name=?");
        statement.setString(1, query);

        ResultSet resultSet = statement.executeQuery();
        ArrayList<Game> singleGame = new ArrayList<>();
        while(resultSet.next()){

            Game game = new Game(

                    resultSet.getInt("id"),
                    resultSet.getString("name"),
                    resultSet.getString("platform"),
                    resultSet.getString("genre"),
                    resultSet.getInt("releaseYear")
            );

            singleGame.add(game);

        }

        return singleGame;

    }

}
